### ISSUE TITLE
Code refactoring and quick responsiveness behaviour fixing

### ISSUE THREAD

**Issue by srlhyo** [srlhyo/poetik#10]
The code can be improved. Better use of utility classes, helpers and general styling leads to less media queries and rather complexity added to it.

Also, when testing the website on mobile, there are some issues with the responsiveness (ex: the header parallex effect is a bit snappy)

**Comment by srlhyo** [comment]
all steps done apart from the shop section, For some reason I can't keep the cards all even. Can you take a look at that? @LailaL88

**Comment by LailaL88** [comment]
I will make poetik show fully
